
["Essence config file"]
	#Mob essence drop chance 0.0 = always, 1.0 = never, 0.5 = 50% chance, default = 0.75
	"Mob Drop Chance" = 0.75
	#Chance that spawner shards drop from spawners, default = 0.0
	"Spawner Shard Drop Chance" = 0.0
	#Amount of shards that drop from spawners, default = 1
	"Spawner Shard Amount Dropped" = 1
	#Essence drop chance from all ores with the forge/ores tag; 0.0 = always, 1.0 = never, 0.5 = 50% chance, default = 0.75
	"All ore drop chance" = 0.75
	#Ore essence drop from ores with the essence:basic_ore tag chance; 0.0 = always, 1.0 = never, 0.5 = 50% chance, default = 0.75
	"Basic Ore Drop Chance" = 0.75
	#Ore essence drop from ores with the essence:advanced_ore tag chance; 0.0 = always, 1.0 = never, 0.5 = 50% chance, default = 0.80
	"Advanced Ore Drop Chance" = 0.8
	#Ore essence drop from ores with the essence:elite_ore tag chance; 0.0 = always, 1.0 = never, 0.5 = 50% chance, default = 0.85
	"Elite Ore Drop Chance" = 0.85

