
["WorkspaceDead Config"]
	#id of item used to open Nether Portal. Blank = default fire.
	"Nether Portal Opening Item" = "projectdead:netherigniter"
	#Color of clouds. Blank for default. "128,128,128" (RGB) otherwise.
	"Cloud Color" = ""

